apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-task
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "s@bisus.net"
    privateKeySecretRef:
      name: letsencrypt-task
    solvers:
    - http01:
        ingress:
          class: traefik 
