name: Local deployment

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: 'Local deployment'
      run: "./scripts/local-deploy.sh ${{ github.sha }}"
