name: Local deploy

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'node-hostname'
        namespace: 'node-hostname'
        chart: 'app'
        token: '${{ github.token }}'
        values: |
          version: ${{ github.sha }}
        value-files: >-
          [
            "values.yaml",
          ]
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
