name: Pipeline 

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  step1:
    uses: sunnes/task1/.github/workflows/test-build.yml@debug
  step2:
    needs: step1
    uses: sunnes/task1/.github/workflows/build.yml@debug
  step3:
    needs: step2
    uses: sunnes/task1/.github/workflows/local-deploy.yml@debug
