name: Pipeline 

on:
  push:
    branches: ['debug']
  workflow_dispatch:

jobs:
  step_1:
    uses: sunnes/task1/.github/workflows/test-build.yml@debug
  step_2:
    needs: test
    uses: sunnes/task1/.github/workflows/build.yml@debug
  step_3:
    needs: build
    uses: sunnes/task1/.github/workflows/local-deploy.yml@debug
