name: Pipeline 

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  test:
    uses: sunnes/task1/.github/workflows/test-build.yml@main
  build:
    needs: test
    uses: sunnes/task1/.github/workflows/build.yml@main
  deploy:
    needs: build
    uses: sunnes/task1/.github/workflows/local-deploy.yml@main
    if: false
