name: Pipeline 
on:
  workflow_dispatch:

jobs:
  test:
    uses: .github/workflows/test-build.yml@debug
  build:
    needs: test
    uses: .github/workflows/build.yml@debug
  deploy:
    needs: build
    uses: .github/workflows/local-deploy.yml@debug