name: Pipeline 
on:
  workflow_dispatch:

jobs:
  test:
    uses: sunnes/test1/test-build.yml@debug
  build:
    needs: test
    uses: sunnes/test1/build.yml@debug
  deploy:
    needs: build
    uses: sunnes/test1/local-deploy.yml@debug